/*
  These files serve to be an introduction to the LLVM API, as well as LLVM IR.

  Our "hello world" goal is to print the first 14 numbers of the Fibonacci sequence
  from two functions, one generated by the LLVM API and one hand-written in LLVM IR.

  Visit the other files in this folder to view compilation instructions, but remember to experiment and play around!
  Because clang is just a frontend for LLVM, all files in this folder are inherently related.
  For example, try using `clang -emit-llvm` on fibonacci.cpp or changing the output type to .ll on generate_fibonacci.cpp
  to see how closely it lines up with handwritten_fibonacci.ll
*/

#include <stdio.h>

extern "C" int fib(int);

int main (int argc, char **argv) {
  for (int i = 0; i < 14; ++i) {
    printf("%d ", fib(i));
  }

  return 0;
}