
GB_Mnemonic :: enum {
  ADC;
  ADD;
  AND;
  BIT;
  CALL;
  CCF;
  CP;
  CPL;
  DAA;
  DEC;
  DI;
  EI;
  HALT;
  INC;
  JP;
  JR;
  LD;
  LDH;
  NOP;
  OR;
  POP;
  PUSH;
  RES;
  RET;
  RETI;
  RL;
  RLA;
  RLC;
  RLCA;
  RR;
  RRA;
  RRC;
  RRCA;
  RST;
  SBC;
  SCF;
  SET;
  SLA;
  SRA;
  SRL;
  STOP;
  SUB;
  SWAP;
  XOR;
  PREFIX;

  ILLEGAL_D3;
  ILLEGAL_DB;
  ILLEGAL_DD;
  ILLEGAL_E3;
  ILLEGAL_E4;
  ILLEGAL_EB;
  ILLEGAL_EC;
  ILLEGAL_ED;
  ILLEGAL_F4;
  ILLEGAL_FC;
  ILLEGAL_FD;
}

GB_Operand :: enum {
  NONE;

  A;
  B;
  C;
  D;
  E;
  H;
  L;

  AF;
  BC;
  DE;
  HL;

  SP;
  SPI;
  SP_e8;
  PC;

  n8;
  n16;
  e8;

  a8;
  a16;
  CIND;
  BCIND;
  DEIND;
  HLIND;
  HLI;
  HLD;
  a8IND;
  a16IND;

  u3;
  VEC;

  Z;
  NZ;
  NC;
}

gb_load_instruction_data :: () -> unprefixed: [] GB_Instruction, cbprefixed: [] GB_Instruction {
  #import "Json";

  Json_Opcode_Table :: struct #type_info_no_size_complaint {
    _0x00: Json_Opcode_Data; @JsonName(0x00)
    _0x01: Json_Opcode_Data; @JsonName(0x01)
    _0x02: Json_Opcode_Data; @JsonName(0x02)
    _0x03: Json_Opcode_Data; @JsonName(0x03)
    _0x04: Json_Opcode_Data; @JsonName(0x04)
    _0x05: Json_Opcode_Data; @JsonName(0x05)
    _0x06: Json_Opcode_Data; @JsonName(0x06)
    _0x07: Json_Opcode_Data; @JsonName(0x07)
    _0x08: Json_Opcode_Data; @JsonName(0x08)
    _0x09: Json_Opcode_Data; @JsonName(0x09)
    _0x0A: Json_Opcode_Data; @JsonName(0x0A)
    _0x0B: Json_Opcode_Data; @JsonName(0x0B)
    _0x0C: Json_Opcode_Data; @JsonName(0x0C)
    _0x0D: Json_Opcode_Data; @JsonName(0x0D)
    _0x0E: Json_Opcode_Data; @JsonName(0x0E)
    _0x0F: Json_Opcode_Data; @JsonName(0x0F)
    _0x10: Json_Opcode_Data; @JsonName(0x10)
    _0x11: Json_Opcode_Data; @JsonName(0x11)
    _0x12: Json_Opcode_Data; @JsonName(0x12)
    _0x13: Json_Opcode_Data; @JsonName(0x13)
    _0x14: Json_Opcode_Data; @JsonName(0x14)
    _0x15: Json_Opcode_Data; @JsonName(0x15)
    _0x16: Json_Opcode_Data; @JsonName(0x16)
    _0x17: Json_Opcode_Data; @JsonName(0x17)
    _0x18: Json_Opcode_Data; @JsonName(0x18)
    _0x19: Json_Opcode_Data; @JsonName(0x19)
    _0x1A: Json_Opcode_Data; @JsonName(0x1A)
    _0x1B: Json_Opcode_Data; @JsonName(0x1B)
    _0x1C: Json_Opcode_Data; @JsonName(0x1C)
    _0x1D: Json_Opcode_Data; @JsonName(0x1D)
    _0x1E: Json_Opcode_Data; @JsonName(0x1E)
    _0x1F: Json_Opcode_Data; @JsonName(0x1F)
    _0x20: Json_Opcode_Data; @JsonName(0x20)
    _0x21: Json_Opcode_Data; @JsonName(0x21)
    _0x22: Json_Opcode_Data; @JsonName(0x22)
    _0x23: Json_Opcode_Data; @JsonName(0x23)
    _0x24: Json_Opcode_Data; @JsonName(0x24)
    _0x25: Json_Opcode_Data; @JsonName(0x25)
    _0x26: Json_Opcode_Data; @JsonName(0x26)
    _0x27: Json_Opcode_Data; @JsonName(0x27)
    _0x28: Json_Opcode_Data; @JsonName(0x28)
    _0x29: Json_Opcode_Data; @JsonName(0x29)
    _0x2A: Json_Opcode_Data; @JsonName(0x2A)
    _0x2B: Json_Opcode_Data; @JsonName(0x2B)
    _0x2C: Json_Opcode_Data; @JsonName(0x2C)
    _0x2D: Json_Opcode_Data; @JsonName(0x2D)
    _0x2E: Json_Opcode_Data; @JsonName(0x2E)
    _0x2F: Json_Opcode_Data; @JsonName(0x2F)
    _0x30: Json_Opcode_Data; @JsonName(0x30)
    _0x31: Json_Opcode_Data; @JsonName(0x31)
    _0x32: Json_Opcode_Data; @JsonName(0x32)
    _0x33: Json_Opcode_Data; @JsonName(0x33)
    _0x34: Json_Opcode_Data; @JsonName(0x34)
    _0x35: Json_Opcode_Data; @JsonName(0x35)
    _0x36: Json_Opcode_Data; @JsonName(0x36)
    _0x37: Json_Opcode_Data; @JsonName(0x37)
    _0x38: Json_Opcode_Data; @JsonName(0x38)
    _0x39: Json_Opcode_Data; @JsonName(0x39)
    _0x3A: Json_Opcode_Data; @JsonName(0x3A)
    _0x3B: Json_Opcode_Data; @JsonName(0x3B)
    _0x3C: Json_Opcode_Data; @JsonName(0x3C)
    _0x3D: Json_Opcode_Data; @JsonName(0x3D)
    _0x3E: Json_Opcode_Data; @JsonName(0x3E)
    _0x3F: Json_Opcode_Data; @JsonName(0x3F)
    _0x40: Json_Opcode_Data; @JsonName(0x40)
    _0x41: Json_Opcode_Data; @JsonName(0x41)
    _0x42: Json_Opcode_Data; @JsonName(0x42)
    _0x43: Json_Opcode_Data; @JsonName(0x43)
    _0x44: Json_Opcode_Data; @JsonName(0x44)
    _0x45: Json_Opcode_Data; @JsonName(0x45)
    _0x46: Json_Opcode_Data; @JsonName(0x46)
    _0x47: Json_Opcode_Data; @JsonName(0x47)
    _0x48: Json_Opcode_Data; @JsonName(0x48)
    _0x49: Json_Opcode_Data; @JsonName(0x49)
    _0x4A: Json_Opcode_Data; @JsonName(0x4A)
    _0x4B: Json_Opcode_Data; @JsonName(0x4B)
    _0x4C: Json_Opcode_Data; @JsonName(0x4C)
    _0x4D: Json_Opcode_Data; @JsonName(0x4D)
    _0x4E: Json_Opcode_Data; @JsonName(0x4E)
    _0x4F: Json_Opcode_Data; @JsonName(0x4F)
    _0x50: Json_Opcode_Data; @JsonName(0x50)
    _0x51: Json_Opcode_Data; @JsonName(0x51)
    _0x52: Json_Opcode_Data; @JsonName(0x52)
    _0x53: Json_Opcode_Data; @JsonName(0x53)
    _0x54: Json_Opcode_Data; @JsonName(0x54)
    _0x55: Json_Opcode_Data; @JsonName(0x55)
    _0x56: Json_Opcode_Data; @JsonName(0x56)
    _0x57: Json_Opcode_Data; @JsonName(0x57)
    _0x58: Json_Opcode_Data; @JsonName(0x58)
    _0x59: Json_Opcode_Data; @JsonName(0x59)
    _0x5A: Json_Opcode_Data; @JsonName(0x5A)
    _0x5B: Json_Opcode_Data; @JsonName(0x5B)
    _0x5C: Json_Opcode_Data; @JsonName(0x5C)
    _0x5D: Json_Opcode_Data; @JsonName(0x5D)
    _0x5E: Json_Opcode_Data; @JsonName(0x5E)
    _0x5F: Json_Opcode_Data; @JsonName(0x5F)
    _0x60: Json_Opcode_Data; @JsonName(0x60)
    _0x61: Json_Opcode_Data; @JsonName(0x61)
    _0x62: Json_Opcode_Data; @JsonName(0x62)
    _0x63: Json_Opcode_Data; @JsonName(0x63)
    _0x64: Json_Opcode_Data; @JsonName(0x64)
    _0x65: Json_Opcode_Data; @JsonName(0x65)
    _0x66: Json_Opcode_Data; @JsonName(0x66)
    _0x67: Json_Opcode_Data; @JsonName(0x67)
    _0x68: Json_Opcode_Data; @JsonName(0x68)
    _0x69: Json_Opcode_Data; @JsonName(0x69)
    _0x6A: Json_Opcode_Data; @JsonName(0x6A)
    _0x6B: Json_Opcode_Data; @JsonName(0x6B)
    _0x6C: Json_Opcode_Data; @JsonName(0x6C)
    _0x6D: Json_Opcode_Data; @JsonName(0x6D)
    _0x6E: Json_Opcode_Data; @JsonName(0x6E)
    _0x6F: Json_Opcode_Data; @JsonName(0x6F)
    _0x70: Json_Opcode_Data; @JsonName(0x70)
    _0x71: Json_Opcode_Data; @JsonName(0x71)
    _0x72: Json_Opcode_Data; @JsonName(0x72)
    _0x73: Json_Opcode_Data; @JsonName(0x73)
    _0x74: Json_Opcode_Data; @JsonName(0x74)
    _0x75: Json_Opcode_Data; @JsonName(0x75)
    _0x76: Json_Opcode_Data; @JsonName(0x76)
    _0x77: Json_Opcode_Data; @JsonName(0x77)
    _0x78: Json_Opcode_Data; @JsonName(0x78)
    _0x79: Json_Opcode_Data; @JsonName(0x79)
    _0x7A: Json_Opcode_Data; @JsonName(0x7A)
    _0x7B: Json_Opcode_Data; @JsonName(0x7B)
    _0x7C: Json_Opcode_Data; @JsonName(0x7C)
    _0x7D: Json_Opcode_Data; @JsonName(0x7D)
    _0x7E: Json_Opcode_Data; @JsonName(0x7E)
    _0x7F: Json_Opcode_Data; @JsonName(0x7F)
    _0x80: Json_Opcode_Data; @JsonName(0x80)
    _0x81: Json_Opcode_Data; @JsonName(0x81)
    _0x82: Json_Opcode_Data; @JsonName(0x82)
    _0x83: Json_Opcode_Data; @JsonName(0x83)
    _0x84: Json_Opcode_Data; @JsonName(0x84)
    _0x85: Json_Opcode_Data; @JsonName(0x85)
    _0x86: Json_Opcode_Data; @JsonName(0x86)
    _0x87: Json_Opcode_Data; @JsonName(0x87)
    _0x88: Json_Opcode_Data; @JsonName(0x88)
    _0x89: Json_Opcode_Data; @JsonName(0x89)
    _0x8A: Json_Opcode_Data; @JsonName(0x8A)
    _0x8B: Json_Opcode_Data; @JsonName(0x8B)
    _0x8C: Json_Opcode_Data; @JsonName(0x8C)
    _0x8D: Json_Opcode_Data; @JsonName(0x8D)
    _0x8E: Json_Opcode_Data; @JsonName(0x8E)
    _0x8F: Json_Opcode_Data; @JsonName(0x8F)
    _0x90: Json_Opcode_Data; @JsonName(0x90)
    _0x91: Json_Opcode_Data; @JsonName(0x91)
    _0x92: Json_Opcode_Data; @JsonName(0x92)
    _0x93: Json_Opcode_Data; @JsonName(0x93)
    _0x94: Json_Opcode_Data; @JsonName(0x94)
    _0x95: Json_Opcode_Data; @JsonName(0x95)
    _0x96: Json_Opcode_Data; @JsonName(0x96)
    _0x97: Json_Opcode_Data; @JsonName(0x97)
    _0x98: Json_Opcode_Data; @JsonName(0x98)
    _0x99: Json_Opcode_Data; @JsonName(0x99)
    _0x9A: Json_Opcode_Data; @JsonName(0x9A)
    _0x9B: Json_Opcode_Data; @JsonName(0x9B)
    _0x9C: Json_Opcode_Data; @JsonName(0x9C)
    _0x9D: Json_Opcode_Data; @JsonName(0x9D)
    _0x9E: Json_Opcode_Data; @JsonName(0x9E)
    _0x9F: Json_Opcode_Data; @JsonName(0x9F)
    _0xA0: Json_Opcode_Data; @JsonName(0xA0)
    _0xA1: Json_Opcode_Data; @JsonName(0xA1)
    _0xA2: Json_Opcode_Data; @JsonName(0xA2)
    _0xA3: Json_Opcode_Data; @JsonName(0xA3)
    _0xA4: Json_Opcode_Data; @JsonName(0xA4)
    _0xA5: Json_Opcode_Data; @JsonName(0xA5)
    _0xA6: Json_Opcode_Data; @JsonName(0xA6)
    _0xA7: Json_Opcode_Data; @JsonName(0xA7)
    _0xA8: Json_Opcode_Data; @JsonName(0xA8)
    _0xA9: Json_Opcode_Data; @JsonName(0xA9)
    _0xAA: Json_Opcode_Data; @JsonName(0xAA)
    _0xAB: Json_Opcode_Data; @JsonName(0xAB)
    _0xAC: Json_Opcode_Data; @JsonName(0xAC)
    _0xAD: Json_Opcode_Data; @JsonName(0xAD)
    _0xAE: Json_Opcode_Data; @JsonName(0xAE)
    _0xAF: Json_Opcode_Data; @JsonName(0xAF)
    _0xB0: Json_Opcode_Data; @JsonName(0xB0)
    _0xB1: Json_Opcode_Data; @JsonName(0xB1)
    _0xB2: Json_Opcode_Data; @JsonName(0xB2)
    _0xB3: Json_Opcode_Data; @JsonName(0xB3)
    _0xB4: Json_Opcode_Data; @JsonName(0xB4)
    _0xB5: Json_Opcode_Data; @JsonName(0xB5)
    _0xB6: Json_Opcode_Data; @JsonName(0xB6)
    _0xB7: Json_Opcode_Data; @JsonName(0xB7)
    _0xB8: Json_Opcode_Data; @JsonName(0xB8)
    _0xB9: Json_Opcode_Data; @JsonName(0xB9)
    _0xBA: Json_Opcode_Data; @JsonName(0xBA)
    _0xBB: Json_Opcode_Data; @JsonName(0xBB)
    _0xBC: Json_Opcode_Data; @JsonName(0xBC)
    _0xBD: Json_Opcode_Data; @JsonName(0xBD)
    _0xBE: Json_Opcode_Data; @JsonName(0xBE)
    _0xBF: Json_Opcode_Data; @JsonName(0xBF)
    _0xC0: Json_Opcode_Data; @JsonName(0xC0)
    _0xC1: Json_Opcode_Data; @JsonName(0xC1)
    _0xC2: Json_Opcode_Data; @JsonName(0xC2)
    _0xC3: Json_Opcode_Data; @JsonName(0xC3)
    _0xC4: Json_Opcode_Data; @JsonName(0xC4)
    _0xC5: Json_Opcode_Data; @JsonName(0xC5)
    _0xC6: Json_Opcode_Data; @JsonName(0xC6)
    _0xC7: Json_Opcode_Data; @JsonName(0xC7)
    _0xC8: Json_Opcode_Data; @JsonName(0xC8)
    _0xC9: Json_Opcode_Data; @JsonName(0xC9)
    _0xCA: Json_Opcode_Data; @JsonName(0xCA)
    _0xCB: Json_Opcode_Data; @JsonName(0xCB)
    _0xCC: Json_Opcode_Data; @JsonName(0xCC)
    _0xCD: Json_Opcode_Data; @JsonName(0xCD)
    _0xCE: Json_Opcode_Data; @JsonName(0xCE)
    _0xCF: Json_Opcode_Data; @JsonName(0xCF)
    _0xD0: Json_Opcode_Data; @JsonName(0xD0)
    _0xD1: Json_Opcode_Data; @JsonName(0xD1)
    _0xD2: Json_Opcode_Data; @JsonName(0xD2)
    _0xD3: Json_Opcode_Data; @JsonName(0xD3)
    _0xD4: Json_Opcode_Data; @JsonName(0xD4)
    _0xD5: Json_Opcode_Data; @JsonName(0xD5)
    _0xD6: Json_Opcode_Data; @JsonName(0xD6)
    _0xD7: Json_Opcode_Data; @JsonName(0xD7)
    _0xD8: Json_Opcode_Data; @JsonName(0xD8)
    _0xD9: Json_Opcode_Data; @JsonName(0xD9)
    _0xDA: Json_Opcode_Data; @JsonName(0xDA)
    _0xDB: Json_Opcode_Data; @JsonName(0xDB)
    _0xDC: Json_Opcode_Data; @JsonName(0xDC)
    _0xDD: Json_Opcode_Data; @JsonName(0xDD)
    _0xDE: Json_Opcode_Data; @JsonName(0xDE)
    _0xDF: Json_Opcode_Data; @JsonName(0xDF)
    _0xE0: Json_Opcode_Data; @JsonName(0xE0)
    _0xE1: Json_Opcode_Data; @JsonName(0xE1)
    _0xE2: Json_Opcode_Data; @JsonName(0xE2)
    _0xE3: Json_Opcode_Data; @JsonName(0xE3)
    _0xE4: Json_Opcode_Data; @JsonName(0xE4)
    _0xE5: Json_Opcode_Data; @JsonName(0xE5)
    _0xE6: Json_Opcode_Data; @JsonName(0xE6)
    _0xE7: Json_Opcode_Data; @JsonName(0xE7)
    _0xE8: Json_Opcode_Data; @JsonName(0xE8)
    _0xE9: Json_Opcode_Data; @JsonName(0xE9)
    _0xEA: Json_Opcode_Data; @JsonName(0xEA)
    _0xEB: Json_Opcode_Data; @JsonName(0xEB)
    _0xEC: Json_Opcode_Data; @JsonName(0xEC)
    _0xED: Json_Opcode_Data; @JsonName(0xED)
    _0xEE: Json_Opcode_Data; @JsonName(0xEE)
    _0xEF: Json_Opcode_Data; @JsonName(0xEF)
    _0xF0: Json_Opcode_Data; @JsonName(0xF0)
    _0xF1: Json_Opcode_Data; @JsonName(0xF1)
    _0xF2: Json_Opcode_Data; @JsonName(0xF2)
    _0xF3: Json_Opcode_Data; @JsonName(0xF3)
    _0xF4: Json_Opcode_Data; @JsonName(0xF4)
    _0xF5: Json_Opcode_Data; @JsonName(0xF5)
    _0xF6: Json_Opcode_Data; @JsonName(0xF6)
    _0xF7: Json_Opcode_Data; @JsonName(0xF7)
    _0xF8: Json_Opcode_Data; @JsonName(0xF8)
    _0xF9: Json_Opcode_Data; @JsonName(0xF9)
    _0xFA: Json_Opcode_Data; @JsonName(0xFA)
    _0xFB: Json_Opcode_Data; @JsonName(0xFB)
    _0xFC: Json_Opcode_Data; @JsonName(0xFC)
    _0xFD: Json_Opcode_Data; @JsonName(0xFD)
    _0xFE: Json_Opcode_Data; @JsonName(0xFE)
    _0xFF: Json_Opcode_Data; @JsonName(0xFF)

    #overlay (_0x00) opcodes: [0x100] Json_Opcode_Data;

    Json_Opcode_Data :: struct {
      mnemonic: string;
      bytes: int;
      cycles: [] int;
      operands: [] Json_Operand;
      immediate: bool;
      flags: *JSON_Value;

      Json_Operand :: struct {
        name: string;
        immediate: bool;
        increment: bool;
        decrement: bool;
        bytes: int;
      }
    }
  }

  Json_Instruction_Set :: struct {
    unprefixed: Json_Opcode_Table;
    cbprefixed: Json_Opcode_Table;

    #overlay (unprefixed) set: [2] Json_Opcode_Table;
  };
  unprefixed := NewArray(256, GB_Instruction);
  cbprefixed := NewArray(256, GB_Instruction);
  push_allocator(temp);

  load_result, instrs := json_parse_file(OPCODE_DESCRIPTOR_PATH, Json_Instruction_Set);
  assert (load_result);
  instruction_sets := [] GB_Instruction.[unprefixed, cbprefixed];
  for set, set_index: instrs.set {
    for opcode, opcode_idx: set.opcodes {
      new_instr := *instruction_sets[set_index][opcode_idx];
      new_instr.size = cast(u16) opcode.bytes;
      new_instr.t_states = ifx opcode.cycles.count > 1 then -1 else opcode.cycles[0];
      m_info := type_info(GB_Mnemonic);
      found_mnemonic := false;
      for m_info.names {
        if it == opcode.mnemonic {
          found_mnemonic = true;
          new_instr.mnemonic = cast(GB_Mnemonic) m_info.values[it_index];
        }
      }
      if !found_mnemonic {
        assert(false, "Unrecognized instruction mnemonic: %", opcode.mnemonic);
      }
      op_info := type_info(GB_Operand);

      if opcode.operands.count > 2 {
        assert(new_instr.mnemonic == .LD); // There should only be one...
        new_instr.op1 = .HL;
        new_instr.op2 = .SP_e8;
        continue;
      }

      for * operand, operand_idx: opcode.operands {
        found_operand := false;
        special_operand := false;
        if operand.increment {
          operand.name = sprint("%%", operand.name, "I");
          special_operand = true;
        } else if operand.decrement {
          operand.name = sprint("%%", operand.name, "D");
          special_operand = true;
        } else if !operand.immediate {
          operand.name = sprint("%%", operand.name, "IND");
          special_operand = true;
        }
        for op_info.names {
          if it == operand.name {
            found_operand = true;
            new_instr.op[operand_idx] = cast(GB_Operand) op_info.values[it_index];
          }
        }
        if !found_operand && special_operand then assert(false, "Unrecognized instruction operand: %", operand.name);
        if !found_operand {
          // NOTE: We are probably dealing with an RST vector (0x00, 0x08, 0x10, 0x18, 0x20, 0x28, 0x30, and 0x38),
          // or an unsigned 3-bit integer (u3).
          val, success, _ := string_to_int(advance(operand.name, 1), 16);
          if (success) {
            assert(operand.immediate, "Unhandled special operand: % with opcode: %\n", operand.*, opcode_idx);
            new_instr.op[operand_idx] = .VEC;
            new_instr.vec_or_u3 = cast(u8) val;
          } else {
            val, success, _ = string_to_int(operand.name);
            if (success && operand.name.count == 1) {
              new_instr.op[operand_idx] = .u3;
              new_instr.vec_or_u3 = cast(u8) val;
            } else {
              assert(false, "Unrecognized instruction operand: %", operand.name);
            }
          }
        }
      }
    }
  }

  return unprefixed, cbprefixed;
}

gb_generate_instruction_vtable :: () -> unprefixed: [] gb_instr_proc, prefixed: [] gb_instr_proc {
  result_unprefixed := NewArray(256, gb_instr_proc);
  result_cbprefixed := NewArray(256, gb_instr_proc);
  result_unprefixed[0] = #procedure_of_call gb_instr_nop(null, .NONE, .NONE, 0);
  result_unprefixed[1] = #procedure_of_call gb_instr_ld(null, .BC, .n16, 0);
  result_unprefixed[2] = #procedure_of_call gb_instr_ld(null, .BCIND, .A, 0);
  result_unprefixed[3] = #procedure_of_call gb_instr_inc(null, .BC, .NONE, 0);
  result_unprefixed[4] = #procedure_of_call gb_instr_inc(null, .B, .NONE, 0);
  result_unprefixed[5] = #procedure_of_call gb_instr_dec(null, .B, .NONE, 0);
  result_unprefixed[6] = #procedure_of_call gb_instr_ld(null, .B, .n8, 0);
  result_unprefixed[7] = #procedure_of_call gb_instr_rlca(null, .NONE, .NONE, 0);
  result_unprefixed[8] = #procedure_of_call gb_instr_ld(null, .a16IND, .SP, 0);
  result_unprefixed[9] = #procedure_of_call gb_instr_add(null, .HL, .BC, 0);
  result_unprefixed[10] = #procedure_of_call gb_instr_ld(null, .A, .BCIND, 0);
  result_unprefixed[11] = #procedure_of_call gb_instr_dec(null, .BC, .NONE, 0);
  result_unprefixed[12] = #procedure_of_call gb_instr_inc(null, .C, .NONE, 0);
  result_unprefixed[13] = #procedure_of_call gb_instr_dec(null, .C, .NONE, 0);
  result_unprefixed[14] = #procedure_of_call gb_instr_ld(null, .C, .n8, 0);
  result_unprefixed[15] = #procedure_of_call gb_instr_rrca(null, .NONE, .NONE, 0);
  result_unprefixed[16] = #procedure_of_call gb_instr_stop(null, .n8, .NONE, 0);
  result_unprefixed[17] = #procedure_of_call gb_instr_ld(null, .DE, .n16, 0);
  result_unprefixed[18] = #procedure_of_call gb_instr_ld(null, .DEIND, .A, 0);
  result_unprefixed[19] = #procedure_of_call gb_instr_inc(null, .DE, .NONE, 0);
  result_unprefixed[20] = #procedure_of_call gb_instr_inc(null, .D, .NONE, 0);
  result_unprefixed[21] = #procedure_of_call gb_instr_dec(null, .D, .NONE, 0);
  result_unprefixed[22] = #procedure_of_call gb_instr_ld(null, .D, .n8, 0);
  result_unprefixed[23] = #procedure_of_call gb_instr_rla(null, .NONE, .NONE, 0);
  result_unprefixed[24] = #procedure_of_call gb_instr_jr(null, .e8, .NONE, 0);
  result_unprefixed[25] = #procedure_of_call gb_instr_add(null, .HL, .DE, 0);
  result_unprefixed[26] = #procedure_of_call gb_instr_ld(null, .A, .DEIND, 0);
  result_unprefixed[27] = #procedure_of_call gb_instr_dec(null, .DE, .NONE, 0);
  result_unprefixed[28] = #procedure_of_call gb_instr_inc(null, .E, .NONE, 0);
  result_unprefixed[29] = #procedure_of_call gb_instr_dec(null, .E, .NONE, 0);
  result_unprefixed[30] = #procedure_of_call gb_instr_ld(null, .E, .n8, 0);
  result_unprefixed[31] = #procedure_of_call gb_instr_rra(null, .NONE, .NONE, 0);
  result_unprefixed[32] = #procedure_of_call gb_instr_jr(null, .NZ, .e8, 0);
  result_unprefixed[33] = #procedure_of_call gb_instr_ld(null, .HL, .n16, 0);
  result_unprefixed[34] = #procedure_of_call gb_instr_ld(null, .HLI, .A, 0);
  result_unprefixed[35] = #procedure_of_call gb_instr_inc(null, .HL, .NONE, 0);
  result_unprefixed[36] = #procedure_of_call gb_instr_inc(null, .H, .NONE, 0);
  result_unprefixed[37] = #procedure_of_call gb_instr_dec(null, .H, .NONE, 0);
  result_unprefixed[38] = #procedure_of_call gb_instr_ld(null, .H, .n8, 0);
  result_unprefixed[39] = #procedure_of_call gb_instr_daa(null, .NONE, .NONE, 0);
  result_unprefixed[40] = #procedure_of_call gb_instr_jr(null, .Z, .e8, 0);
  result_unprefixed[41] = #procedure_of_call gb_instr_add(null, .HL, .HL, 0);
  result_unprefixed[42] = #procedure_of_call gb_instr_ld(null, .A, .HLI, 0);
  result_unprefixed[43] = #procedure_of_call gb_instr_dec(null, .HL, .NONE, 0);
  result_unprefixed[44] = #procedure_of_call gb_instr_inc(null, .L, .NONE, 0);
  result_unprefixed[45] = #procedure_of_call gb_instr_dec(null, .L, .NONE, 0);
  result_unprefixed[46] = #procedure_of_call gb_instr_ld(null, .L, .n8, 0);
  result_unprefixed[47] = #procedure_of_call gb_instr_cpl(null, .NONE, .NONE, 0);
  result_unprefixed[48] = #procedure_of_call gb_instr_jr(null, .NC, .e8, 0);
  result_unprefixed[49] = #procedure_of_call gb_instr_ld(null, .SP, .n16, 0);
  result_unprefixed[50] = #procedure_of_call gb_instr_ld(null, .HLD, .A, 0);
  result_unprefixed[51] = #procedure_of_call gb_instr_inc(null, .SP, .NONE, 0);
  result_unprefixed[52] = #procedure_of_call gb_instr_inc(null, .HLIND, .NONE, 0);
  result_unprefixed[53] = #procedure_of_call gb_instr_dec(null, .HLIND, .NONE, 0);
  result_unprefixed[54] = #procedure_of_call gb_instr_ld(null, .HLIND, .n8, 0);
  result_unprefixed[55] = #procedure_of_call gb_instr_scf(null, .NONE, .NONE, 0);
  result_unprefixed[56] = #procedure_of_call gb_instr_jr(null, .C, .e8, 0);
  result_unprefixed[57] = #procedure_of_call gb_instr_add(null, .HL, .SP, 0);
  result_unprefixed[58] = #procedure_of_call gb_instr_ld(null, .A, .HLD, 0);
  result_unprefixed[59] = #procedure_of_call gb_instr_dec(null, .SP, .NONE, 0);
  result_unprefixed[60] = #procedure_of_call gb_instr_inc(null, .A, .NONE, 0);
  result_unprefixed[61] = #procedure_of_call gb_instr_dec(null, .A, .NONE, 0);
  result_unprefixed[62] = #procedure_of_call gb_instr_ld(null, .A, .n8, 0);
  result_unprefixed[63] = #procedure_of_call gb_instr_ccf(null, .NONE, .NONE, 0);
  result_unprefixed[64] = #procedure_of_call gb_instr_ld(null, .B, .B, 0);
  result_unprefixed[65] = #procedure_of_call gb_instr_ld(null, .B, .C, 0);
  result_unprefixed[66] = #procedure_of_call gb_instr_ld(null, .B, .D, 0);
  result_unprefixed[67] = #procedure_of_call gb_instr_ld(null, .B, .E, 0);
  result_unprefixed[68] = #procedure_of_call gb_instr_ld(null, .B, .H, 0);
  result_unprefixed[69] = #procedure_of_call gb_instr_ld(null, .B, .L, 0);
  result_unprefixed[70] = #procedure_of_call gb_instr_ld(null, .B, .HLIND, 0);
  result_unprefixed[71] = #procedure_of_call gb_instr_ld(null, .B, .A, 0);
  result_unprefixed[72] = #procedure_of_call gb_instr_ld(null, .C, .B, 0);
  result_unprefixed[73] = #procedure_of_call gb_instr_ld(null, .C, .C, 0);
  result_unprefixed[74] = #procedure_of_call gb_instr_ld(null, .C, .D, 0);
  result_unprefixed[75] = #procedure_of_call gb_instr_ld(null, .C, .E, 0);
  result_unprefixed[76] = #procedure_of_call gb_instr_ld(null, .C, .H, 0);
  result_unprefixed[77] = #procedure_of_call gb_instr_ld(null, .C, .L, 0);
  result_unprefixed[78] = #procedure_of_call gb_instr_ld(null, .C, .HLIND, 0);
  result_unprefixed[79] = #procedure_of_call gb_instr_ld(null, .C, .A, 0);
  result_unprefixed[80] = #procedure_of_call gb_instr_ld(null, .D, .B, 0);
  result_unprefixed[81] = #procedure_of_call gb_instr_ld(null, .D, .C, 0);
  result_unprefixed[82] = #procedure_of_call gb_instr_ld(null, .D, .D, 0);
  result_unprefixed[83] = #procedure_of_call gb_instr_ld(null, .D, .E, 0);
  result_unprefixed[84] = #procedure_of_call gb_instr_ld(null, .D, .H, 0);
  result_unprefixed[85] = #procedure_of_call gb_instr_ld(null, .D, .L, 0);
  result_unprefixed[86] = #procedure_of_call gb_instr_ld(null, .D, .HLIND, 0);
  result_unprefixed[87] = #procedure_of_call gb_instr_ld(null, .D, .A, 0);
  result_unprefixed[88] = #procedure_of_call gb_instr_ld(null, .E, .B, 0);
  result_unprefixed[89] = #procedure_of_call gb_instr_ld(null, .E, .C, 0);
  result_unprefixed[90] = #procedure_of_call gb_instr_ld(null, .E, .D, 0);
  result_unprefixed[91] = #procedure_of_call gb_instr_ld(null, .E, .E, 0);
  result_unprefixed[92] = #procedure_of_call gb_instr_ld(null, .E, .H, 0);
  result_unprefixed[93] = #procedure_of_call gb_instr_ld(null, .E, .L, 0);
  result_unprefixed[94] = #procedure_of_call gb_instr_ld(null, .E, .HLIND, 0);
  result_unprefixed[95] = #procedure_of_call gb_instr_ld(null, .E, .A, 0);
  result_unprefixed[96] = #procedure_of_call gb_instr_ld(null, .H, .B, 0);
  result_unprefixed[97] = #procedure_of_call gb_instr_ld(null, .H, .C, 0);
  result_unprefixed[98] = #procedure_of_call gb_instr_ld(null, .H, .D, 0);
  result_unprefixed[99] = #procedure_of_call gb_instr_ld(null, .H, .E, 0);
  result_unprefixed[100] = #procedure_of_call gb_instr_ld(null, .H, .H, 0);
  result_unprefixed[101] = #procedure_of_call gb_instr_ld(null, .H, .L, 0);
  result_unprefixed[102] = #procedure_of_call gb_instr_ld(null, .H, .HLIND, 0);
  result_unprefixed[103] = #procedure_of_call gb_instr_ld(null, .H, .A, 0);
  result_unprefixed[104] = #procedure_of_call gb_instr_ld(null, .L, .B, 0);
  result_unprefixed[105] = #procedure_of_call gb_instr_ld(null, .L, .C, 0);
  result_unprefixed[106] = #procedure_of_call gb_instr_ld(null, .L, .D, 0);
  result_unprefixed[107] = #procedure_of_call gb_instr_ld(null, .L, .E, 0);
  result_unprefixed[108] = #procedure_of_call gb_instr_ld(null, .L, .H, 0);
  result_unprefixed[109] = #procedure_of_call gb_instr_ld(null, .L, .L, 0);
  result_unprefixed[110] = #procedure_of_call gb_instr_ld(null, .L, .HLIND, 0);
  result_unprefixed[111] = #procedure_of_call gb_instr_ld(null, .L, .A, 0);
  result_unprefixed[112] = #procedure_of_call gb_instr_ld(null, .HLIND, .B, 0);
  result_unprefixed[113] = #procedure_of_call gb_instr_ld(null, .HLIND, .C, 0);
  result_unprefixed[114] = #procedure_of_call gb_instr_ld(null, .HLIND, .D, 0);
  result_unprefixed[115] = #procedure_of_call gb_instr_ld(null, .HLIND, .E, 0);
  result_unprefixed[116] = #procedure_of_call gb_instr_ld(null, .HLIND, .H, 0);
  result_unprefixed[117] = #procedure_of_call gb_instr_ld(null, .HLIND, .L, 0);
  result_unprefixed[118] = #procedure_of_call gb_instr_halt(null, .NONE, .NONE, 0);
  result_unprefixed[119] = #procedure_of_call gb_instr_ld(null, .HLIND, .A, 0);
  result_unprefixed[120] = #procedure_of_call gb_instr_ld(null, .A, .B, 0);
  result_unprefixed[121] = #procedure_of_call gb_instr_ld(null, .A, .C, 0);
  result_unprefixed[122] = #procedure_of_call gb_instr_ld(null, .A, .D, 0);
  result_unprefixed[123] = #procedure_of_call gb_instr_ld(null, .A, .E, 0);
  result_unprefixed[124] = #procedure_of_call gb_instr_ld(null, .A, .H, 0);
  result_unprefixed[125] = #procedure_of_call gb_instr_ld(null, .A, .L, 0);
  result_unprefixed[126] = #procedure_of_call gb_instr_ld(null, .A, .HLIND, 0);
  result_unprefixed[127] = #procedure_of_call gb_instr_ld(null, .A, .A, 0);
  result_unprefixed[128] = #procedure_of_call gb_instr_add(null, .A, .B, 0);
  result_unprefixed[129] = #procedure_of_call gb_instr_add(null, .A, .C, 0);
  result_unprefixed[130] = #procedure_of_call gb_instr_add(null, .A, .D, 0);
  result_unprefixed[131] = #procedure_of_call gb_instr_add(null, .A, .E, 0);
  result_unprefixed[132] = #procedure_of_call gb_instr_add(null, .A, .H, 0);
  result_unprefixed[133] = #procedure_of_call gb_instr_add(null, .A, .L, 0);
  result_unprefixed[134] = #procedure_of_call gb_instr_add(null, .A, .HLIND, 0);
  result_unprefixed[135] = #procedure_of_call gb_instr_add(null, .A, .A, 0);
  result_unprefixed[136] = #procedure_of_call gb_instr_adc(null, .A, .B, 0);
  result_unprefixed[137] = #procedure_of_call gb_instr_adc(null, .A, .C, 0);
  result_unprefixed[138] = #procedure_of_call gb_instr_adc(null, .A, .D, 0);
  result_unprefixed[139] = #procedure_of_call gb_instr_adc(null, .A, .E, 0);
  result_unprefixed[140] = #procedure_of_call gb_instr_adc(null, .A, .H, 0);
  result_unprefixed[141] = #procedure_of_call gb_instr_adc(null, .A, .L, 0);
  result_unprefixed[142] = #procedure_of_call gb_instr_adc(null, .A, .HLIND, 0);
  result_unprefixed[143] = #procedure_of_call gb_instr_adc(null, .A, .A, 0);
  result_unprefixed[144] = #procedure_of_call gb_instr_sub(null, .A, .B, 0);
  result_unprefixed[145] = #procedure_of_call gb_instr_sub(null, .A, .C, 0);
  result_unprefixed[146] = #procedure_of_call gb_instr_sub(null, .A, .D, 0);
  result_unprefixed[147] = #procedure_of_call gb_instr_sub(null, .A, .E, 0);
  result_unprefixed[148] = #procedure_of_call gb_instr_sub(null, .A, .H, 0);
  result_unprefixed[149] = #procedure_of_call gb_instr_sub(null, .A, .L, 0);
  result_unprefixed[150] = #procedure_of_call gb_instr_sub(null, .A, .HLIND, 0);
  result_unprefixed[151] = #procedure_of_call gb_instr_sub(null, .A, .A, 0);
  result_unprefixed[152] = #procedure_of_call gb_instr_sbc(null, .A, .B, 0);
  result_unprefixed[153] = #procedure_of_call gb_instr_sbc(null, .A, .C, 0);
  result_unprefixed[154] = #procedure_of_call gb_instr_sbc(null, .A, .D, 0);
  result_unprefixed[155] = #procedure_of_call gb_instr_sbc(null, .A, .E, 0);
  result_unprefixed[156] = #procedure_of_call gb_instr_sbc(null, .A, .H, 0);
  result_unprefixed[157] = #procedure_of_call gb_instr_sbc(null, .A, .L, 0);
  result_unprefixed[158] = #procedure_of_call gb_instr_sbc(null, .A, .HLIND, 0);
  result_unprefixed[159] = #procedure_of_call gb_instr_sbc(null, .A, .A, 0);
  result_unprefixed[160] = #procedure_of_call gb_instr_and(null, .A, .B, 0);
  result_unprefixed[161] = #procedure_of_call gb_instr_and(null, .A, .C, 0);
  result_unprefixed[162] = #procedure_of_call gb_instr_and(null, .A, .D, 0);
  result_unprefixed[163] = #procedure_of_call gb_instr_and(null, .A, .E, 0);
  result_unprefixed[164] = #procedure_of_call gb_instr_and(null, .A, .H, 0);
  result_unprefixed[165] = #procedure_of_call gb_instr_and(null, .A, .L, 0);
  result_unprefixed[166] = #procedure_of_call gb_instr_and(null, .A, .HLIND, 0);
  result_unprefixed[167] = #procedure_of_call gb_instr_and(null, .A, .A, 0);
  result_unprefixed[168] = #procedure_of_call gb_instr_xor(null, .A, .B, 0);
  result_unprefixed[169] = #procedure_of_call gb_instr_xor(null, .A, .C, 0);
  result_unprefixed[170] = #procedure_of_call gb_instr_xor(null, .A, .D, 0);
  result_unprefixed[171] = #procedure_of_call gb_instr_xor(null, .A, .E, 0);
  result_unprefixed[172] = #procedure_of_call gb_instr_xor(null, .A, .H, 0);
  result_unprefixed[173] = #procedure_of_call gb_instr_xor(null, .A, .L, 0);
  result_unprefixed[174] = #procedure_of_call gb_instr_xor(null, .A, .HLIND, 0);
  result_unprefixed[175] = #procedure_of_call gb_instr_xor(null, .A, .A, 0);
  result_unprefixed[176] = #procedure_of_call gb_instr_or(null, .A, .B, 0);
  result_unprefixed[177] = #procedure_of_call gb_instr_or(null, .A, .C, 0);
  result_unprefixed[178] = #procedure_of_call gb_instr_or(null, .A, .D, 0);
  result_unprefixed[179] = #procedure_of_call gb_instr_or(null, .A, .E, 0);
  result_unprefixed[180] = #procedure_of_call gb_instr_or(null, .A, .H, 0);
  result_unprefixed[181] = #procedure_of_call gb_instr_or(null, .A, .L, 0);
  result_unprefixed[182] = #procedure_of_call gb_instr_or(null, .A, .HLIND, 0);
  result_unprefixed[183] = #procedure_of_call gb_instr_or(null, .A, .A, 0);
  result_unprefixed[184] = #procedure_of_call gb_instr_cp(null, .A, .B, 0);
  result_unprefixed[185] = #procedure_of_call gb_instr_cp(null, .A, .C, 0);
  result_unprefixed[186] = #procedure_of_call gb_instr_cp(null, .A, .D, 0);
  result_unprefixed[187] = #procedure_of_call gb_instr_cp(null, .A, .E, 0);
  result_unprefixed[188] = #procedure_of_call gb_instr_cp(null, .A, .H, 0);
  result_unprefixed[189] = #procedure_of_call gb_instr_cp(null, .A, .L, 0);
  result_unprefixed[190] = #procedure_of_call gb_instr_cp(null, .A, .HLIND, 0);
  result_unprefixed[191] = #procedure_of_call gb_instr_cp(null, .A, .A, 0);
  result_unprefixed[192] = #procedure_of_call gb_instr_ret(null, .NZ, .NONE, 0);
  result_unprefixed[193] = #procedure_of_call gb_instr_pop(null, .BC, .NONE, 0);
  result_unprefixed[194] = #procedure_of_call gb_instr_jp(null, .NZ, .a16, 0);
  result_unprefixed[195] = #procedure_of_call gb_instr_jp(null, .a16, .NONE, 0);
  result_unprefixed[196] = #procedure_of_call gb_instr_call(null, .NZ, .a16, 0);
  result_unprefixed[197] = #procedure_of_call gb_instr_push(null, .BC, .NONE, 0);
  result_unprefixed[198] = #procedure_of_call gb_instr_add(null, .A, .n8, 0);
  result_unprefixed[199] = #procedure_of_call gb_instr_rst(null, .VEC, .NONE, 0);
  result_unprefixed[200] = #procedure_of_call gb_instr_ret(null, .Z, .NONE, 0);
  result_unprefixed[201] = #procedure_of_call gb_instr_ret(null, .NONE, .NONE, 0);
  result_unprefixed[202] = #procedure_of_call gb_instr_jp(null, .Z, .a16, 0);
  result_unprefixed[203] = #procedure_of_call gb_instr_prefix(null, .NONE, .NONE, 0);
  result_unprefixed[204] = #procedure_of_call gb_instr_call(null, .Z, .a16, 0);
  result_unprefixed[205] = #procedure_of_call gb_instr_call(null, .a16, .NONE, 0);
  result_unprefixed[206] = #procedure_of_call gb_instr_adc(null, .A, .n8, 0);
  result_unprefixed[207] = #procedure_of_call gb_instr_rst(null, .VEC, .NONE, 8);
  result_unprefixed[208] = #procedure_of_call gb_instr_ret(null, .NC, .NONE, 0);
  result_unprefixed[209] = #procedure_of_call gb_instr_pop(null, .DE, .NONE, 0);
  result_unprefixed[210] = #procedure_of_call gb_instr_jp(null, .NC, .a16, 0);
  result_unprefixed[211] = #procedure_of_call gb_instr_nop(null, .NONE, .NONE, 0);
  result_unprefixed[212] = #procedure_of_call gb_instr_call(null, .NC, .a16, 0);
  result_unprefixed[213] = #procedure_of_call gb_instr_push(null, .DE, .NONE, 0);
  result_unprefixed[214] = #procedure_of_call gb_instr_sub(null, .A, .n8, 0);
  result_unprefixed[215] = #procedure_of_call gb_instr_rst(null, .VEC, .NONE, 16);
  result_unprefixed[216] = #procedure_of_call gb_instr_ret(null, .C, .NONE, 0);
  result_unprefixed[217] = #procedure_of_call gb_instr_reti(null, .NONE, .NONE, 0);
  result_unprefixed[218] = #procedure_of_call gb_instr_jp(null, .C, .a16, 0);
  result_unprefixed[219] = #procedure_of_call gb_instr_nop(null, .NONE, .NONE, 0);
  result_unprefixed[220] = #procedure_of_call gb_instr_call(null, .C, .a16, 0);
  result_unprefixed[221] = #procedure_of_call gb_instr_nop(null, .NONE, .NONE, 0);
  result_unprefixed[222] = #procedure_of_call gb_instr_sbc(null, .A, .n8, 0);
  result_unprefixed[223] = #procedure_of_call gb_instr_rst(null, .VEC, .NONE, 24);
  result_unprefixed[224] = #procedure_of_call gb_instr_ldh(null, .a8IND, .A, 0);
  result_unprefixed[225] = #procedure_of_call gb_instr_pop(null, .HL, .NONE, 0);
  result_unprefixed[226] = #procedure_of_call gb_instr_ldh(null, .CIND, .A, 0);
  result_unprefixed[227] = #procedure_of_call gb_instr_nop(null, .NONE, .NONE, 0);
  result_unprefixed[228] = #procedure_of_call gb_instr_nop(null, .NONE, .NONE, 0);
  result_unprefixed[229] = #procedure_of_call gb_instr_push(null, .HL, .NONE, 0);
  result_unprefixed[230] = #procedure_of_call gb_instr_and(null, .A, .n8, 0);
  result_unprefixed[231] = #procedure_of_call gb_instr_rst(null, .VEC, .NONE, 32);
  result_unprefixed[232] = #procedure_of_call gb_instr_add(null, .SP, .e8, 0);
  result_unprefixed[233] = #procedure_of_call gb_instr_jp(null, .HL, .NONE, 0);
  result_unprefixed[234] = #procedure_of_call gb_instr_ld(null, .a16IND, .A, 0);
  result_unprefixed[235] = #procedure_of_call gb_instr_nop(null, .NONE, .NONE, 0);
  result_unprefixed[236] = #procedure_of_call gb_instr_nop(null, .NONE, .NONE, 0);
  result_unprefixed[237] = #procedure_of_call gb_instr_nop(null, .NONE, .NONE, 0);
  result_unprefixed[238] = #procedure_of_call gb_instr_xor(null, .A, .n8, 0);
  result_unprefixed[239] = #procedure_of_call gb_instr_rst(null, .VEC, .NONE, 40);
  result_unprefixed[240] = #procedure_of_call gb_instr_ldh(null, .A, .a8IND, 0);
  result_unprefixed[241] = #procedure_of_call gb_instr_pop(null, .AF, .NONE, 0);
  result_unprefixed[242] = #procedure_of_call gb_instr_ldh(null, .A, .CIND, 0);
  result_unprefixed[243] = #procedure_of_call gb_instr_di(null, .NONE, .NONE, 0);
  result_unprefixed[244] = #procedure_of_call gb_instr_nop(null, .NONE, .NONE, 0);
  result_unprefixed[245] = #procedure_of_call gb_instr_push(null, .AF, .NONE, 0);
  result_unprefixed[246] = #procedure_of_call gb_instr_or(null, .A, .n8, 0);
  result_unprefixed[247] = #procedure_of_call gb_instr_rst(null, .VEC, .NONE, 48);
  result_unprefixed[248] = #procedure_of_call gb_instr_ld(null, .HL, .SP_e8, 0);
  result_unprefixed[249] = #procedure_of_call gb_instr_ld(null, .SP, .HL, 0);
  result_unprefixed[250] = #procedure_of_call gb_instr_ld(null, .A, .a16IND, 0);
  result_unprefixed[251] = #procedure_of_call gb_instr_ei(null, .NONE, .NONE, 0);
  result_unprefixed[252] = #procedure_of_call gb_instr_nop(null, .NONE, .NONE, 0);
  result_unprefixed[253] = #procedure_of_call gb_instr_nop(null, .NONE, .NONE, 0);
  result_unprefixed[254] = #procedure_of_call gb_instr_cp(null, .A, .n8, 0);
  result_unprefixed[255] = #procedure_of_call gb_instr_rst(null, .VEC, .NONE, 56);
  result_cbprefixed[0] = #procedure_of_call gb_instr_rlc(null, .B, .NONE, 0);
  result_cbprefixed[1] = #procedure_of_call gb_instr_rlc(null, .C, .NONE, 0);
  result_cbprefixed[2] = #procedure_of_call gb_instr_rlc(null, .D, .NONE, 0);
  result_cbprefixed[3] = #procedure_of_call gb_instr_rlc(null, .E, .NONE, 0);
  result_cbprefixed[4] = #procedure_of_call gb_instr_rlc(null, .H, .NONE, 0);
  result_cbprefixed[5] = #procedure_of_call gb_instr_rlc(null, .L, .NONE, 0);
  result_cbprefixed[6] = #procedure_of_call gb_instr_rlc(null, .HLIND, .NONE, 0);
  result_cbprefixed[7] = #procedure_of_call gb_instr_rlc(null, .A, .NONE, 0);
  result_cbprefixed[8] = #procedure_of_call gb_instr_rrc(null, .B, .NONE, 0);
  result_cbprefixed[9] = #procedure_of_call gb_instr_rrc(null, .C, .NONE, 0);
  result_cbprefixed[10] = #procedure_of_call gb_instr_rrc(null, .D, .NONE, 0);
  result_cbprefixed[11] = #procedure_of_call gb_instr_rrc(null, .E, .NONE, 0);
  result_cbprefixed[12] = #procedure_of_call gb_instr_rrc(null, .H, .NONE, 0);
  result_cbprefixed[13] = #procedure_of_call gb_instr_rrc(null, .L, .NONE, 0);
  result_cbprefixed[14] = #procedure_of_call gb_instr_rrc(null, .HLIND, .NONE, 0);
  result_cbprefixed[15] = #procedure_of_call gb_instr_rrc(null, .A, .NONE, 0);
  result_cbprefixed[16] = #procedure_of_call gb_instr_rl(null, .B, .NONE, 0);
  result_cbprefixed[17] = #procedure_of_call gb_instr_rl(null, .C, .NONE, 0);
  result_cbprefixed[18] = #procedure_of_call gb_instr_rl(null, .D, .NONE, 0);
  result_cbprefixed[19] = #procedure_of_call gb_instr_rl(null, .E, .NONE, 0);
  result_cbprefixed[20] = #procedure_of_call gb_instr_rl(null, .H, .NONE, 0);
  result_cbprefixed[21] = #procedure_of_call gb_instr_rl(null, .L, .NONE, 0);
  result_cbprefixed[22] = #procedure_of_call gb_instr_rl(null, .HLIND, .NONE, 0);
  result_cbprefixed[23] = #procedure_of_call gb_instr_rl(null, .A, .NONE, 0);
  result_cbprefixed[24] = #procedure_of_call gb_instr_rr(null, .B, .NONE, 0);
  result_cbprefixed[25] = #procedure_of_call gb_instr_rr(null, .C, .NONE, 0);
  result_cbprefixed[26] = #procedure_of_call gb_instr_rr(null, .D, .NONE, 0);
  result_cbprefixed[27] = #procedure_of_call gb_instr_rr(null, .E, .NONE, 0);
  result_cbprefixed[28] = #procedure_of_call gb_instr_rr(null, .H, .NONE, 0);
  result_cbprefixed[29] = #procedure_of_call gb_instr_rr(null, .L, .NONE, 0);
  result_cbprefixed[30] = #procedure_of_call gb_instr_rr(null, .HLIND, .NONE, 0);
  result_cbprefixed[31] = #procedure_of_call gb_instr_rr(null, .A, .NONE, 0);
  result_cbprefixed[32] = #procedure_of_call gb_instr_sla(null, .B, .NONE, 0);
  result_cbprefixed[33] = #procedure_of_call gb_instr_sla(null, .C, .NONE, 0);
  result_cbprefixed[34] = #procedure_of_call gb_instr_sla(null, .D, .NONE, 0);
  result_cbprefixed[35] = #procedure_of_call gb_instr_sla(null, .E, .NONE, 0);
  result_cbprefixed[36] = #procedure_of_call gb_instr_sla(null, .H, .NONE, 0);
  result_cbprefixed[37] = #procedure_of_call gb_instr_sla(null, .L, .NONE, 0);
  result_cbprefixed[38] = #procedure_of_call gb_instr_sla(null, .HLIND, .NONE, 0);
  result_cbprefixed[39] = #procedure_of_call gb_instr_sla(null, .A, .NONE, 0);
  result_cbprefixed[40] = #procedure_of_call gb_instr_sra(null, .B, .NONE, 0);
  result_cbprefixed[41] = #procedure_of_call gb_instr_sra(null, .C, .NONE, 0);
  result_cbprefixed[42] = #procedure_of_call gb_instr_sra(null, .D, .NONE, 0);
  result_cbprefixed[43] = #procedure_of_call gb_instr_sra(null, .E, .NONE, 0);
  result_cbprefixed[44] = #procedure_of_call gb_instr_sra(null, .H, .NONE, 0);
  result_cbprefixed[45] = #procedure_of_call gb_instr_sra(null, .L, .NONE, 0);
  result_cbprefixed[46] = #procedure_of_call gb_instr_sra(null, .HLIND, .NONE, 0);
  result_cbprefixed[47] = #procedure_of_call gb_instr_sra(null, .A, .NONE, 0);
  result_cbprefixed[48] = #procedure_of_call gb_instr_swap(null, .B, .NONE, 0);
  result_cbprefixed[49] = #procedure_of_call gb_instr_swap(null, .C, .NONE, 0);
  result_cbprefixed[50] = #procedure_of_call gb_instr_swap(null, .D, .NONE, 0);
  result_cbprefixed[51] = #procedure_of_call gb_instr_swap(null, .E, .NONE, 0);
  result_cbprefixed[52] = #procedure_of_call gb_instr_swap(null, .H, .NONE, 0);
  result_cbprefixed[53] = #procedure_of_call gb_instr_swap(null, .L, .NONE, 0);
  result_cbprefixed[54] = #procedure_of_call gb_instr_swap(null, .HLIND, .NONE, 0);
  result_cbprefixed[55] = #procedure_of_call gb_instr_swap(null, .A, .NONE, 0);
  result_cbprefixed[56] = #procedure_of_call gb_instr_srl(null, .B, .NONE, 0);
  result_cbprefixed[57] = #procedure_of_call gb_instr_srl(null, .C, .NONE, 0);
  result_cbprefixed[58] = #procedure_of_call gb_instr_srl(null, .D, .NONE, 0);
  result_cbprefixed[59] = #procedure_of_call gb_instr_srl(null, .E, .NONE, 0);
  result_cbprefixed[60] = #procedure_of_call gb_instr_srl(null, .H, .NONE, 0);
  result_cbprefixed[61] = #procedure_of_call gb_instr_srl(null, .L, .NONE, 0);
  result_cbprefixed[62] = #procedure_of_call gb_instr_srl(null, .HLIND, .NONE, 0);
  result_cbprefixed[63] = #procedure_of_call gb_instr_srl(null, .A, .NONE, 0);
  result_cbprefixed[64] = #procedure_of_call gb_instr_bit(null, .u3, .B, 0);
  result_cbprefixed[65] = #procedure_of_call gb_instr_bit(null, .u3, .C, 0);
  result_cbprefixed[66] = #procedure_of_call gb_instr_bit(null, .u3, .D, 0);
  result_cbprefixed[67] = #procedure_of_call gb_instr_bit(null, .u3, .E, 0);
  result_cbprefixed[68] = #procedure_of_call gb_instr_bit(null, .u3, .H, 0);
  result_cbprefixed[69] = #procedure_of_call gb_instr_bit(null, .u3, .L, 0);
  result_cbprefixed[70] = #procedure_of_call gb_instr_bit(null, .u3, .HLIND, 0);
  result_cbprefixed[71] = #procedure_of_call gb_instr_bit(null, .u3, .A, 0);
  result_cbprefixed[72] = #procedure_of_call gb_instr_bit(null, .u3, .B, 1);
  result_cbprefixed[73] = #procedure_of_call gb_instr_bit(null, .u3, .C, 1);
  result_cbprefixed[74] = #procedure_of_call gb_instr_bit(null, .u3, .D, 1);
  result_cbprefixed[75] = #procedure_of_call gb_instr_bit(null, .u3, .E, 1);
  result_cbprefixed[76] = #procedure_of_call gb_instr_bit(null, .u3, .H, 1);
  result_cbprefixed[77] = #procedure_of_call gb_instr_bit(null, .u3, .L, 1);
  result_cbprefixed[78] = #procedure_of_call gb_instr_bit(null, .u3, .HLIND, 1);
  result_cbprefixed[79] = #procedure_of_call gb_instr_bit(null, .u3, .A, 1);
  result_cbprefixed[80] = #procedure_of_call gb_instr_bit(null, .u3, .B, 2);
  result_cbprefixed[81] = #procedure_of_call gb_instr_bit(null, .u3, .C, 2);
  result_cbprefixed[82] = #procedure_of_call gb_instr_bit(null, .u3, .D, 2);
  result_cbprefixed[83] = #procedure_of_call gb_instr_bit(null, .u3, .E, 2);
  result_cbprefixed[84] = #procedure_of_call gb_instr_bit(null, .u3, .H, 2);
  result_cbprefixed[85] = #procedure_of_call gb_instr_bit(null, .u3, .L, 2);
  result_cbprefixed[86] = #procedure_of_call gb_instr_bit(null, .u3, .HLIND, 2);
  result_cbprefixed[87] = #procedure_of_call gb_instr_bit(null, .u3, .A, 2);
  result_cbprefixed[88] = #procedure_of_call gb_instr_bit(null, .u3, .B, 3);
  result_cbprefixed[89] = #procedure_of_call gb_instr_bit(null, .u3, .C, 3);
  result_cbprefixed[90] = #procedure_of_call gb_instr_bit(null, .u3, .D, 3);
  result_cbprefixed[91] = #procedure_of_call gb_instr_bit(null, .u3, .E, 3);
  result_cbprefixed[92] = #procedure_of_call gb_instr_bit(null, .u3, .H, 3);
  result_cbprefixed[93] = #procedure_of_call gb_instr_bit(null, .u3, .L, 3);
  result_cbprefixed[94] = #procedure_of_call gb_instr_bit(null, .u3, .HLIND, 3);
  result_cbprefixed[95] = #procedure_of_call gb_instr_bit(null, .u3, .A, 3);
  result_cbprefixed[96] = #procedure_of_call gb_instr_bit(null, .u3, .B, 4);
  result_cbprefixed[97] = #procedure_of_call gb_instr_bit(null, .u3, .C, 4);
  result_cbprefixed[98] = #procedure_of_call gb_instr_bit(null, .u3, .D, 4);
  result_cbprefixed[99] = #procedure_of_call gb_instr_bit(null, .u3, .E, 4);
  result_cbprefixed[100] = #procedure_of_call gb_instr_bit(null, .u3, .H, 4);
  result_cbprefixed[101] = #procedure_of_call gb_instr_bit(null, .u3, .L, 4);
  result_cbprefixed[102] = #procedure_of_call gb_instr_bit(null, .u3, .HLIND, 4);
  result_cbprefixed[103] = #procedure_of_call gb_instr_bit(null, .u3, .A, 4);
  result_cbprefixed[104] = #procedure_of_call gb_instr_bit(null, .u3, .B, 5);
  result_cbprefixed[105] = #procedure_of_call gb_instr_bit(null, .u3, .C, 5);
  result_cbprefixed[106] = #procedure_of_call gb_instr_bit(null, .u3, .D, 5);
  result_cbprefixed[107] = #procedure_of_call gb_instr_bit(null, .u3, .E, 5);
  result_cbprefixed[108] = #procedure_of_call gb_instr_bit(null, .u3, .H, 5);
  result_cbprefixed[109] = #procedure_of_call gb_instr_bit(null, .u3, .L, 5);
  result_cbprefixed[110] = #procedure_of_call gb_instr_bit(null, .u3, .HLIND, 5);
  result_cbprefixed[111] = #procedure_of_call gb_instr_bit(null, .u3, .A, 5);
  result_cbprefixed[112] = #procedure_of_call gb_instr_bit(null, .u3, .B, 6);
  result_cbprefixed[113] = #procedure_of_call gb_instr_bit(null, .u3, .C, 6);
  result_cbprefixed[114] = #procedure_of_call gb_instr_bit(null, .u3, .D, 6);
  result_cbprefixed[115] = #procedure_of_call gb_instr_bit(null, .u3, .E, 6);
  result_cbprefixed[116] = #procedure_of_call gb_instr_bit(null, .u3, .H, 6);
  result_cbprefixed[117] = #procedure_of_call gb_instr_bit(null, .u3, .L, 6);
  result_cbprefixed[118] = #procedure_of_call gb_instr_bit(null, .u3, .HLIND, 6);
  result_cbprefixed[119] = #procedure_of_call gb_instr_bit(null, .u3, .A, 6);
  result_cbprefixed[120] = #procedure_of_call gb_instr_bit(null, .u3, .B, 7);
  result_cbprefixed[121] = #procedure_of_call gb_instr_bit(null, .u3, .C, 7);
  result_cbprefixed[122] = #procedure_of_call gb_instr_bit(null, .u3, .D, 7);
  result_cbprefixed[123] = #procedure_of_call gb_instr_bit(null, .u3, .E, 7);
  result_cbprefixed[124] = #procedure_of_call gb_instr_bit(null, .u3, .H, 7);
  result_cbprefixed[125] = #procedure_of_call gb_instr_bit(null, .u3, .L, 7);
  result_cbprefixed[126] = #procedure_of_call gb_instr_bit(null, .u3, .HLIND, 7);
  result_cbprefixed[127] = #procedure_of_call gb_instr_bit(null, .u3, .A, 7);
  result_cbprefixed[128] = #procedure_of_call gb_instr_res(null, .u3, .B, 0);
  result_cbprefixed[129] = #procedure_of_call gb_instr_res(null, .u3, .C, 0);
  result_cbprefixed[130] = #procedure_of_call gb_instr_res(null, .u3, .D, 0);
  result_cbprefixed[131] = #procedure_of_call gb_instr_res(null, .u3, .E, 0);
  result_cbprefixed[132] = #procedure_of_call gb_instr_res(null, .u3, .H, 0);
  result_cbprefixed[133] = #procedure_of_call gb_instr_res(null, .u3, .L, 0);
  result_cbprefixed[134] = #procedure_of_call gb_instr_res(null, .u3, .HLIND, 0);
  result_cbprefixed[135] = #procedure_of_call gb_instr_res(null, .u3, .A, 0);
  result_cbprefixed[136] = #procedure_of_call gb_instr_res(null, .u3, .B, 1);
  result_cbprefixed[137] = #procedure_of_call gb_instr_res(null, .u3, .C, 1);
  result_cbprefixed[138] = #procedure_of_call gb_instr_res(null, .u3, .D, 1);
  result_cbprefixed[139] = #procedure_of_call gb_instr_res(null, .u3, .E, 1);
  result_cbprefixed[140] = #procedure_of_call gb_instr_res(null, .u3, .H, 1);
  result_cbprefixed[141] = #procedure_of_call gb_instr_res(null, .u3, .L, 1);
  result_cbprefixed[142] = #procedure_of_call gb_instr_res(null, .u3, .HLIND, 1);
  result_cbprefixed[143] = #procedure_of_call gb_instr_res(null, .u3, .A, 1);
  result_cbprefixed[144] = #procedure_of_call gb_instr_res(null, .u3, .B, 2);
  result_cbprefixed[145] = #procedure_of_call gb_instr_res(null, .u3, .C, 2);
  result_cbprefixed[146] = #procedure_of_call gb_instr_res(null, .u3, .D, 2);
  result_cbprefixed[147] = #procedure_of_call gb_instr_res(null, .u3, .E, 2);
  result_cbprefixed[148] = #procedure_of_call gb_instr_res(null, .u3, .H, 2);
  result_cbprefixed[149] = #procedure_of_call gb_instr_res(null, .u3, .L, 2);
  result_cbprefixed[150] = #procedure_of_call gb_instr_res(null, .u3, .HLIND, 2);
  result_cbprefixed[151] = #procedure_of_call gb_instr_res(null, .u3, .A, 2);
  result_cbprefixed[152] = #procedure_of_call gb_instr_res(null, .u3, .B, 3);
  result_cbprefixed[153] = #procedure_of_call gb_instr_res(null, .u3, .C, 3);
  result_cbprefixed[154] = #procedure_of_call gb_instr_res(null, .u3, .D, 3);
  result_cbprefixed[155] = #procedure_of_call gb_instr_res(null, .u3, .E, 3);
  result_cbprefixed[156] = #procedure_of_call gb_instr_res(null, .u3, .H, 3);
  result_cbprefixed[157] = #procedure_of_call gb_instr_res(null, .u3, .L, 3);
  result_cbprefixed[158] = #procedure_of_call gb_instr_res(null, .u3, .HLIND, 3);
  result_cbprefixed[159] = #procedure_of_call gb_instr_res(null, .u3, .A, 3);
  result_cbprefixed[160] = #procedure_of_call gb_instr_res(null, .u3, .B, 4);
  result_cbprefixed[161] = #procedure_of_call gb_instr_res(null, .u3, .C, 4);
  result_cbprefixed[162] = #procedure_of_call gb_instr_res(null, .u3, .D, 4);
  result_cbprefixed[163] = #procedure_of_call gb_instr_res(null, .u3, .E, 4);
  result_cbprefixed[164] = #procedure_of_call gb_instr_res(null, .u3, .H, 4);
  result_cbprefixed[165] = #procedure_of_call gb_instr_res(null, .u3, .L, 4);
  result_cbprefixed[166] = #procedure_of_call gb_instr_res(null, .u3, .HLIND, 4);
  result_cbprefixed[167] = #procedure_of_call gb_instr_res(null, .u3, .A, 4);
  result_cbprefixed[168] = #procedure_of_call gb_instr_res(null, .u3, .B, 5);
  result_cbprefixed[169] = #procedure_of_call gb_instr_res(null, .u3, .C, 5);
  result_cbprefixed[170] = #procedure_of_call gb_instr_res(null, .u3, .D, 5);
  result_cbprefixed[171] = #procedure_of_call gb_instr_res(null, .u3, .E, 5);
  result_cbprefixed[172] = #procedure_of_call gb_instr_res(null, .u3, .H, 5);
  result_cbprefixed[173] = #procedure_of_call gb_instr_res(null, .u3, .L, 5);
  result_cbprefixed[174] = #procedure_of_call gb_instr_res(null, .u3, .HLIND, 5);
  result_cbprefixed[175] = #procedure_of_call gb_instr_res(null, .u3, .A, 5);
  result_cbprefixed[176] = #procedure_of_call gb_instr_res(null, .u3, .B, 6);
  result_cbprefixed[177] = #procedure_of_call gb_instr_res(null, .u3, .C, 6);
  result_cbprefixed[178] = #procedure_of_call gb_instr_res(null, .u3, .D, 6);
  result_cbprefixed[179] = #procedure_of_call gb_instr_res(null, .u3, .E, 6);
  result_cbprefixed[180] = #procedure_of_call gb_instr_res(null, .u3, .H, 6);
  result_cbprefixed[181] = #procedure_of_call gb_instr_res(null, .u3, .L, 6);
  result_cbprefixed[182] = #procedure_of_call gb_instr_res(null, .u3, .HLIND, 6);
  result_cbprefixed[183] = #procedure_of_call gb_instr_res(null, .u3, .A, 6);
  result_cbprefixed[184] = #procedure_of_call gb_instr_res(null, .u3, .B, 7);
  result_cbprefixed[185] = #procedure_of_call gb_instr_res(null, .u3, .C, 7);
  result_cbprefixed[186] = #procedure_of_call gb_instr_res(null, .u3, .D, 7);
  result_cbprefixed[187] = #procedure_of_call gb_instr_res(null, .u3, .E, 7);
  result_cbprefixed[188] = #procedure_of_call gb_instr_res(null, .u3, .H, 7);
  result_cbprefixed[189] = #procedure_of_call gb_instr_res(null, .u3, .L, 7);
  result_cbprefixed[190] = #procedure_of_call gb_instr_res(null, .u3, .HLIND, 7);
  result_cbprefixed[191] = #procedure_of_call gb_instr_res(null, .u3, .A, 7);
  result_cbprefixed[192] = #procedure_of_call gb_instr_set(null, .u3, .B, 0);
  result_cbprefixed[193] = #procedure_of_call gb_instr_set(null, .u3, .C, 0);
  result_cbprefixed[194] = #procedure_of_call gb_instr_set(null, .u3, .D, 0);
  result_cbprefixed[195] = #procedure_of_call gb_instr_set(null, .u3, .E, 0);
  result_cbprefixed[196] = #procedure_of_call gb_instr_set(null, .u3, .H, 0);
  result_cbprefixed[197] = #procedure_of_call gb_instr_set(null, .u3, .L, 0);
  result_cbprefixed[198] = #procedure_of_call gb_instr_set(null, .u3, .HLIND, 0);
  result_cbprefixed[199] = #procedure_of_call gb_instr_set(null, .u3, .A, 0);
  result_cbprefixed[200] = #procedure_of_call gb_instr_set(null, .u3, .B, 1);
  result_cbprefixed[201] = #procedure_of_call gb_instr_set(null, .u3, .C, 1);
  result_cbprefixed[202] = #procedure_of_call gb_instr_set(null, .u3, .D, 1);
  result_cbprefixed[203] = #procedure_of_call gb_instr_set(null, .u3, .E, 1);
  result_cbprefixed[204] = #procedure_of_call gb_instr_set(null, .u3, .H, 1);
  result_cbprefixed[205] = #procedure_of_call gb_instr_set(null, .u3, .L, 1);
  result_cbprefixed[206] = #procedure_of_call gb_instr_set(null, .u3, .HLIND, 1);
  result_cbprefixed[207] = #procedure_of_call gb_instr_set(null, .u3, .A, 1);
  result_cbprefixed[208] = #procedure_of_call gb_instr_set(null, .u3, .B, 2);
  result_cbprefixed[209] = #procedure_of_call gb_instr_set(null, .u3, .C, 2);
  result_cbprefixed[210] = #procedure_of_call gb_instr_set(null, .u3, .D, 2);
  result_cbprefixed[211] = #procedure_of_call gb_instr_set(null, .u3, .E, 2);
  result_cbprefixed[212] = #procedure_of_call gb_instr_set(null, .u3, .H, 2);
  result_cbprefixed[213] = #procedure_of_call gb_instr_set(null, .u3, .L, 2);
  result_cbprefixed[214] = #procedure_of_call gb_instr_set(null, .u3, .HLIND, 2);
  result_cbprefixed[215] = #procedure_of_call gb_instr_set(null, .u3, .A, 2);
  result_cbprefixed[216] = #procedure_of_call gb_instr_set(null, .u3, .B, 3);
  result_cbprefixed[217] = #procedure_of_call gb_instr_set(null, .u3, .C, 3);
  result_cbprefixed[218] = #procedure_of_call gb_instr_set(null, .u3, .D, 3);
  result_cbprefixed[219] = #procedure_of_call gb_instr_set(null, .u3, .E, 3);
  result_cbprefixed[220] = #procedure_of_call gb_instr_set(null, .u3, .H, 3);
  result_cbprefixed[221] = #procedure_of_call gb_instr_set(null, .u3, .L, 3);
  result_cbprefixed[222] = #procedure_of_call gb_instr_set(null, .u3, .HLIND, 3);
  result_cbprefixed[223] = #procedure_of_call gb_instr_set(null, .u3, .A, 3);
  result_cbprefixed[224] = #procedure_of_call gb_instr_set(null, .u3, .B, 4);
  result_cbprefixed[225] = #procedure_of_call gb_instr_set(null, .u3, .C, 4);
  result_cbprefixed[226] = #procedure_of_call gb_instr_set(null, .u3, .D, 4);
  result_cbprefixed[227] = #procedure_of_call gb_instr_set(null, .u3, .E, 4);
  result_cbprefixed[228] = #procedure_of_call gb_instr_set(null, .u3, .H, 4);
  result_cbprefixed[229] = #procedure_of_call gb_instr_set(null, .u3, .L, 4);
  result_cbprefixed[230] = #procedure_of_call gb_instr_set(null, .u3, .HLIND, 4);
  result_cbprefixed[231] = #procedure_of_call gb_instr_set(null, .u3, .A, 4);
  result_cbprefixed[232] = #procedure_of_call gb_instr_set(null, .u3, .B, 5);
  result_cbprefixed[233] = #procedure_of_call gb_instr_set(null, .u3, .C, 5);
  result_cbprefixed[234] = #procedure_of_call gb_instr_set(null, .u3, .D, 5);
  result_cbprefixed[235] = #procedure_of_call gb_instr_set(null, .u3, .E, 5);
  result_cbprefixed[236] = #procedure_of_call gb_instr_set(null, .u3, .H, 5);
  result_cbprefixed[237] = #procedure_of_call gb_instr_set(null, .u3, .L, 5);
  result_cbprefixed[238] = #procedure_of_call gb_instr_set(null, .u3, .HLIND, 5);
  result_cbprefixed[239] = #procedure_of_call gb_instr_set(null, .u3, .A, 5);
  result_cbprefixed[240] = #procedure_of_call gb_instr_set(null, .u3, .B, 6);
  result_cbprefixed[241] = #procedure_of_call gb_instr_set(null, .u3, .C, 6);
  result_cbprefixed[242] = #procedure_of_call gb_instr_set(null, .u3, .D, 6);
  result_cbprefixed[243] = #procedure_of_call gb_instr_set(null, .u3, .E, 6);
  result_cbprefixed[244] = #procedure_of_call gb_instr_set(null, .u3, .H, 6);
  result_cbprefixed[245] = #procedure_of_call gb_instr_set(null, .u3, .L, 6);
  result_cbprefixed[246] = #procedure_of_call gb_instr_set(null, .u3, .HLIND, 6);
  result_cbprefixed[247] = #procedure_of_call gb_instr_set(null, .u3, .A, 6);
  result_cbprefixed[248] = #procedure_of_call gb_instr_set(null, .u3, .B, 7);
  result_cbprefixed[249] = #procedure_of_call gb_instr_set(null, .u3, .C, 7);
  result_cbprefixed[250] = #procedure_of_call gb_instr_set(null, .u3, .D, 7);
  result_cbprefixed[251] = #procedure_of_call gb_instr_set(null, .u3, .E, 7);
  result_cbprefixed[252] = #procedure_of_call gb_instr_set(null, .u3, .H, 7);
  result_cbprefixed[253] = #procedure_of_call gb_instr_set(null, .u3, .L, 7);
  result_cbprefixed[254] = #procedure_of_call gb_instr_set(null, .u3, .HLIND, 7);
  result_cbprefixed[255] = #procedure_of_call gb_instr_set(null, .u3, .A, 7);

  return result_unprefixed, result_cbprefixed;
}